experiment: "rm"

# flow param
hidden_units: [128, 128]
num_layers: 12
flow_type: "affine"
activation: "relu"
shuffle: True

# spline only
num_bins: 20

# affine only
actnorm: true
scale: "sigmoid_p05"

# dependencies
param_activation: "sigmoid"
default_param: 0.9
opt_params: false

num_threads: 1

seed: 42
num_log: 2000

data_param:
  bs: 256
  dset: "ukb_biomarker"
  incl_inds: true
  nan_threshold: 0.95
  seed: 42

use_wandb: true
# how often to sample images
log_sample_freq: 25

epochs: 200

# opt + scheduler
scheduler: "onecycle"
opt: "adam"
lr: 0.001
wd: 0.0
pct_start: 0.3
div_factor: 25
final_div_factor: 10_000
steplr_steps: 32
gamma: 0.9
lr_warmup_epochs: 1
cosine_num_restarts: 5

# run_flow params
add_callbacks: ["modelsummary"]
save_checkpoint: false
log_freq: 25
log: null
project: "ddflow_ukb_biomarker_v0.0"

# trainer
gpus: 0
strategy: null
fast_dev_run: false
log_every_n_steps: 25
grad_clip: 0.0
clip_type: "value"

large_batch: false
soft_max_size: 28
hard_max_size: 28

alternating: false
alternating_steps: 0
main_stage_epochs: 0
lam_stage_epochs: 0
lam_stage_gpus: 0
retain_lr: true
lam_lr: 0.0
lam_wd: 0.0
